### ISSUE TITLE
Debug mode for agents

### ISSUE THREAD

**Issue by yustiks** [tdgunes/ExampleAgent#11]
How can I debug the program? Is it only console writing? 

Can I debug in IDEA? I tried, but it doesn`t work.

**Comment by tdgunes** [comment]
You can use `System.out.println` to print your variables to the terminal. But probably other opponent agents tend to use that too. In order to only see your agent's prints, you can directly write values of your variables to a new file by using, for instance, Java's `BufferedWriter`.

Unfortunately, agents needs to be given as a .class file and programmatically running tournaments with an instantiated agent object requires some deep hacks into the Genius API. I'll get back to you, once I learn more information about this.

**Comment by tdgunes** [comment]
I've added a new content about this. You just need to change run configuration in Intellij. Take a look at [this page](https://github.com/tdgunes/ExampleAgent/wiki/Debugging-your-negotiating-agent).

**Comment by yustiks** [comment]
yes, thank you, it worked
