### ISSUE TITLE
Sorting bids by utility

### ISSUE THREAD

**Issue by jogrundy** [tdgunes/ExampleAgent#13]
Hi I'd like to take an array list of bids and sort them by utility. It seems tricky, as we don't have access to the bids class to create a comparator. is there any other way to do it, other than writing our own short sorting algorithm?

Jo

**Comment by tdgunes** [comment]
Hi Jo,

You can use Java's [TreeMap](https://docs.oracle.com/javase/8/docs/api/java/util/TreeMap.html) data structure.  Rather than using `double` as a key to this data structure, use `Double`. Briefly, difference between these two types (`double` vs `Double`) is `Double` is an Java object that wraps the primitive type `double`, so that a primitive type can be used within Java's data structures. 

To give an example with TreeMap:
```java
Double a = 1.0;
Double b = 2.0;
Double c = 3.0;

TreeMap<Double, String> treeMap = new TreeMap<>();

treeMap.put(c, "Three");
treeMap.put(a, "One");
treeMap.put(b, "Two");

for (Map.Entry<Double, String> entry : treeMap.entrySet()) {
    System.out.println(entry.getKey() + " " + entry.getValue());
}
```

This snippet outputs:
```
1.0 One
2.0 Two
3.0 Three
```

You can use `Bid` instead of `String`. Let me know if that works.

**Comment by jogrundy** [comment]
Hi Taha,

Wouldn’t that cause problems if you have two utilities of bids the same, for different bids?

Jo

**Comment by tdgunes** [comment]
Hi Jo,

In that case, you can use [PriorityQueue](https://docs.oracle.com/javase/7/docs/api/java/util/PriorityQueue.html), but you need to use a new auxiliary class that implements `Comparator` interface and stores its `Bid` object. Another solution is to use `TreeMap` again, but  store  `List<Bid>` as a value instead of just `Bid`.

**Comment by jogrundy** [comment]
Hi Taha,
Thank you for your help, I think I'll use a priority queue, if I can figure out how! But thats part of the fun. 
Cheers,
Jo
