### ISSUE TITLE
Persistent Memory 

### ISSUE THREAD

**Issue by BinQian** [tdgunes/ExampleAgent#19]
Since we are not allowed to use the persistent memory, we are not supposed to dynamically adapt our strategy according to the previous actions during the competition. But Can we adapt our strategy based on the current round of action received from the opponent agent?

**Comment by tdgunes** [comment]
First of all, let me define some terminology to clarify that:

- a **tournament** consists of a number of `negotiation sessions` 
- a **negotiation session** consists of a number of `rounds` within some time frame. 

Since persistent memory is not allowed, agent can not store any information between **negotiation sessions**. In addition to that within a session,  the initiated agent is persistent (not getting reset in each round). Therefore, agent can store the actions received in the previous  rounds.

**Comment by Malawero** [comment]
> Therefore, agent can store the actions received in the previous sessions.

You mean the previous rounds?

**Comment by tdgunes** [comment]
Yes, sorry for the typo.
