### ISSUE TITLE
Bidding strategy

### ISSUE THREAD

**Issue by yustiks** [tdgunes/ExampleAgent#23]
Taha, I want to ask, is it possible to make first 80% not maximum, but random bid? Because it seems that almost every agent maximize their utility and try to learn opponent model, what if we change our model intentionaly for that time? Of cause, it can happen, that our bargain will not be maximum for us, but what if we generate random value in a way when it will not be equal or more then the opponent model is proposed?

**Comment by tdgunes** [comment]
Sorry, but do you mean **how to generate an offer which is more than 0.8 utility** in terms of the preference profile assigned to your agent? If so, have a look [here](https://github.com/tdgunes/ExampleAgent/wiki/Generating-a-random-bid-with-a-utility-threshold).

For your other questions, of course you can make dynamic strategies (which makes changes over time). I am guessing what you are trying to say: Generating a bid which is not the maximum for your agent and for others would result your agent to hide the preferences that are given to you. This sounds like a good strategy, but given that your opponent model is doing very good estimation about others preferences, otherwise your agent might offer some bids that maximizes other agents' utilities.

**Comment by yustiks** [comment]
ok , I think I got an answer here!

**Comment by yustiks** [comment]
thank you!
