### ISSUE TITLE
How does a round finish, according to SAOP?

### ISSUE THREAD

**Issue by HalleyXie** [tdgunes/ExampleAgent#6]
In the example given, in the Round 1 step 3: 

> Party 3 can accept c2 or makes a counter offer. Lets say it accepts this offer.

I suppose this is not really the end of round 1. Should also Party 1 accept this offer before this round finishes?

**Comment by tdgunes** [comment]
I am assuming you are referring to the example that is given about the protocol [here](https://github.com/tdgunes/ExampleAgent/wiki/Stacked-Alternating-Offers-Protocol).  

For your question, **each round ends whenever each agent finishes making an action**. Also stated in the example,  after all parties (`Party 1`, `Party 2` and `Party 3`) makes an action the round passes.  

Let me know if this answers your question, so that I can close this issue.

**Comment by HalleyXie** [comment]
To be precisely, I assume you mean "after all parties (Party 1, Party 2 and Party 3) makes an action and **there is no new offer open** or **if any Party walked away**,  the round passes.". Is it correct?

**Comment by tdgunes** [comment]
**Walking away:** If one of the party leaves the negotiation, the round and the negotiation itself ends.  To round to pass, there must be counter-offers made by parties. Example scenarios can be:

### Scenario 1:
Round 1:
- `Party 1` makes an offer
- `Party 2` agrees to offer
- `Party 3` makes a counter-offer

Round 2:
- `Party 1` agrees to `Party 3`s offer
- `Party 2` agrees to `Party 3`s offer

**Negotiation ends with 2 rounds, `Party 3`'s offer is accepted.**

### Scenario 2:

Round 1:
- `Party 1` makes an offer
- `Party 2` makes a counter-offer
- `Party 3` agrees to offer

Round 2:
- `Party 1` agrees to offer  (by `Party 2`) 

**Negotiation ends with 2 rounds. `Party 2`'s offer is accepted.**

Of course if a party wants to walk-away, it can:

### Scenario 3:

Round 1:
- `Party 1` makes an offer
- `Party 2` makes a counter-offer
- `Party 3` walks-away
  
**Negotiation ends with only 1 round.  No offer is accepted.**

**Comment by HalleyXie** [comment]
it is clear now. thank you.
