### ISSUE TITLE
Costs in the negotiation domain

### ISSUE THREAD

**Issue by Juillermo** [tdgunes/ExampleAgent#8]
Hi Taha!

I am a bit confused about the cost field in the items of an issue (in the xml files for the domains). What are they for?

And I also take the chance to ask whether we know beforehand which is going to be the exact set of domains that will be used for the competition.

Cheers!

**Comment by tdgunes** [comment]
Hi Guillermo,

For your first question, I couldn't be able to find any relevant answers in the Genius manual and javadocs. It seems like this `cost` field was used mostly in domains from 2011-2012. I've contacted to maintainers of the GENIUS. I'll get back to you about this here whenever I hear from them. 

For your second question, if you are asking about the international competition in previous years, each participant was asked to provide a new domain. Only these domains were used in the competition. But if you are asking about the module, I'll be forwarding this question to Enrico. Answer to this is probably going to be in the student wiki, since the question is related to the coursework.

**Comment by tdgunes** [comment]
I have been told that it is just a deprecated field, which is not used any more.

**Comment by Juillermo** [comment]
Thank you for the answers!
